version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: store-mysql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro

  rails-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: store-rails
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails db:seed && bin/rails server -b 0.0.0.0"
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/workspaces/store:cached
    depends_on:
      - mysql

volumes:
  db_data:
