# docker-compose.yml
services:
  mysql:
    image: mysql:8.0
    container_name: store-mysql
    restart: unless-stopped
    env_file:
      - .env.prod
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  rails-app:
    image: gnachy/railshop:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: store-rails
    env_file:
      - .env.prod
    ports:
      - "3000:80"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:

      - .:/rails:cached
    restart: unless-stopped

    command: >
      bash -c "
      bin/rails db:migrate &&
      bin/rails db:seed &&
      ./bin/thrust ./bin/rails server -b 0.0.0.0"
      
volumes:
  db_data:
