apiVersion: v1
kind: Secret
metadata:
  name: rails-secret
  namespace: railshop
type: Opaque
data:
  DB_PASSWORD: cE50RnFlczhranRwUmZNblF5P1MmP05RZkxpTjVxJCR0VFQ=
  DB_USERNAME: cmFpbHM=
  MYSQL_ROOT_PASSWORD: cm9vdA==
  RAILS_MASTER_KEY: OTg3ZDQ5N2QxOGFhNTQxNTVhMGM5MTViZTQ3MzA0MzA=
  SECRET_KEY_BASE: NjkwYjlhZTRkN2FkMDI3YmFjMDAxMDJmMTgzNzk3NTBhYWI3ODhlMTQ4NjYxYjU3MjIyYzU3NDIyZTA1YzdjMDMwNTg4OWEwMzY1OTQzNzU3Y2E0NDFhNjE0N2NlODE2N2NlOGU2YmQ2NTFmZWY5NWE5NGY5Y2RjYjBjNTNhNjY=
