apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: ${{ secrets.CERTIFICATE_AUTHORITY_DATA }}
      server: ${{ secrets.SERVER }}
    name: ${{ secrets.CONTEXT_CLUSTER }}
contexts:
  - context:
      cluster: ${{ secrets.CONTEXT_CLUSTER }}
      user: ${{ secrets.CONTEXT_USER }}
    name: ${{ secrets.CURRENT_CONTEXT }}
current-context: ${{ secrets.CURRENT_CONTEXT }}
kind: Config
preferences: {}
users:
  - name: ${{ secrets.CONTEXT_USER }}
    user:
      client-certificate-data: ${{ secrets.CLIENT_CERTIFICATE_DATA }}
      client-key-data: ${{ secrets.CLIENT_KEY_DATA }}
