name: CD

on:
  push:
    branches:
      - main

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create temporary .env.prod
        run: |
          cat <<EOF > .env.prod
          RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_USERNAME=${{ secrets.DB_USERNAME }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
          GMAIL_USERNAME=${{ secrets.GMAIL_USERNAME }}
          GMAIL_PASSWORD=${{ secrets.GMAIL_PASSWORD }}
          EOF

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Rails app Docker image
        run: |
          docker compose --env-file .env.prod build rails-app

      - name: Push Docker image to Docker Hub
        run: |
          docker push gnachy/railshop:latest

      - name: Prepare Kubernetes deployment
        run: |
          echo "Deployment to Kubernetes would go here."
          echo "For example: kubectl apply -f k8s/"
          # kubectl apply -f k8s/  # Uncomment when cluster is ready

      - name: Remove temporary .env.prod
        run: rm -f .env.prod
